name: CI

on: [push, pull_request]

jobs:
  analyze_and_test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Install + cache Flutter SDK (stable 3.22.0 = Dart 3.4.x)
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.0
          cache: true

      # Cache pub packages for faster runs
      - name: Cache pub
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/.dartServer
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      # Get dependencies
      - run: flutter pub get

      # Static analysis (🔴 fails on any warning/info)
      - run: flutter analyze --fatal-warnings --fatal-infos

      # Unit + widget tests with coverage
      - run: flutter test --coverage

      # Upload coverage artifact (optional)
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage/lcov.info
